package com.manasik.api.common;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Identifier and timestamps shared by every entity.
 *
 * <p>The database also defaults {@code created_at}/{@code updated_at} to
 * {@code now()}, so rows inserted by SQL or a migration are still stamped.
 * Spring's auditing covers the application path; the defaults cover everything
 * else.
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /**
     * Generated by the database via {@code gen_random_uuid()}.
     *
     * <p>{@code GenerationType.UUID} would have Hibernate generate the value
     * instead, which works but bypasses the column default and makes the two
     * sources of truth disagree. Letting Postgres own it keeps one rule.
     */
    @Id
    @GeneratedValue
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Equality by id, and only once the id exists.
     *
     * <p>Two unsaved entities are never equal — including to each other — which
     * is what stops a {@code Set} of new entities from collapsing into one.
     * Uses {@code instanceof} rather than {@code getClass()} so a Hibernate
     * lazy proxy still compares equal to the entity it stands for.
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BaseEntity that)) {
            return false;
        }
        return id != null && Objects.equals(id, that.getId());
    }

    /**
     * Constant, deliberately.
     *
     * <p>An entity's hash must not change when it is persisted and gains an id,
     * or it becomes unfindable in any {@code HashSet} it was added to before
     * the flush.
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
