/**
 * All user-facing copy.
 *
 * <p>Nothing in a component should be a hardcoded string. Two reasons beyond
 * eventual translation: the same concept ends up phrased three different ways
 * across three pages otherwise, and copy changes turn into a grep through JSX.
 *
 * <p>Structure is `section.key`. Placeholders are `{name}` and are filled by
 * `t()` — see ./index.ts.
 */
export const en = {
  common: {
    actions: 'Actions',
    add: 'Add',
    all: 'All',
    cancel: 'Cancel',
    clearFilters: 'Clear filters',
    close: 'Close',
    columns: 'Columns',
    confirm: 'Confirm',
    create: 'Create',
    delete: 'Delete',
    details: 'Details',
    edit: 'Edit',
    export: 'Export',
    filter: 'Filter',
    loading: 'Loading…',
    more: 'More',
    next: 'Next',
    none: 'None',
    notSet: 'Not set',
    of: 'of',
    previous: 'Previous',
    rowsPerPage: 'Rows per page',
    save: 'Save',
    saveChanges: 'Save changes',
    search: 'Search',
    selected: '{count} selected',
    showing: 'Showing {from}–{to} of {total}',
    status: 'Status',
    view: 'View',
    viewAll: 'View all',
  },

  nav: {
    dashboard: 'Dashboard',
    packages: 'Packages',
    pilgrims: 'Pilgrims',
    bookings: 'Bookings',
    payments: 'Payments',
    groups: 'Groups',
    documents: 'Documents',
    settings: 'Settings',
    comingSoon: 'Soon',
  },

  dashboard: {
    title: 'Dashboard',
    greeting: 'Welcome, {name}',
    subtitle: 'What needs attention today.',
    activePilgrims: 'Active pilgrims',
    upcomingDepartures: 'Upcoming departures',
    revenueThisMonth: 'Revenue this month',
    outstandingBalance: 'Outstanding balance',
    pendingDocuments: 'Documents pending review',
    overdueInvoices: 'Overdue invoices',
    recentActivity: 'Recent activity',
    noActivity: 'Nothing has happened yet.',
    nextDepartures: 'Next departures',
    noDepartures: 'No departures scheduled.',
    daysAway: '{count} days away',
    departsToday: 'Departs today',
    needsAttention: 'Needs attention',
    allClear: 'Everything is on track.',
  },

  packages: {
    title: 'Packages',
    subtitle: 'The trips you sell.',
    create: 'New package',
    edit: 'Edit package',
    empty: 'No packages yet',
    emptyHint: 'Create your first package to start taking bookings.',
    name: 'Package name',
    type: 'Type',
    destination: 'Destination',
    departureDate: 'Departure',
    returnDate: 'Return',
    duration: 'Duration',
    durationValue: '{count} days',
    price: 'Price per pilgrim',
    capacity: 'Capacity',
    booked: 'Booked',
    seatsRemaining: 'Seats left',
    seatsOf: '{booked} of {capacity}',
    deposit: 'Deposit',
    paymentDue: 'Payment due',
    description: 'Description',
    inclusions: "What's included",
    exclusions: "What's not included",
    itinerary: 'Itinerary',
    revenueCollected: 'Collected',
    deleteConfirm: 'Delete this package?',
    deleteWarning:
      'Bookings already made against it are kept, but the package can no longer be sold.',
  },

  pilgrims: {
    title: 'Pilgrims',
    subtitle: 'Everyone travelling with you.',
    create: 'Add pilgrim',
    edit: 'Edit pilgrim',
    empty: 'No pilgrims yet',
    emptyHint: 'Add a pilgrim to begin.',
    fullName: 'Full name',
    arabicName: 'Name in Arabic',
    gender: 'Gender',
    dateOfBirth: 'Date of birth',
    age: 'Age',
    nationality: 'Nationality',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    country: 'Country',
    emergencyContact: 'Emergency contact',
    emergencyContactName: 'Contact name',
    emergencyContactPhone: 'Contact phone',
    emergencyContactRelation: 'Relationship',
    passportNumber: 'Passport number',
    passportExpiry: 'Passport expiry',
    visaStatus: 'Visa status',
    pilgrimageType: 'Pilgrimage',
    medicalNotes: 'Medical notes',
    specialRequirements: 'Special requirements',
    documents: 'Documents',
    documentsProgress: '{approved} of {required}',
    balance: 'Balance',
    currentPackage: 'Package',
    currentGroup: 'Group',
    tabOverview: 'Overview',
    tabBookings: 'Bookings',
    tabDocuments: 'Documents',
    tabPayments: 'Payments',
  },

  bookings: {
    title: 'Bookings',
    subtitle: 'Who is booked on what.',
    create: 'New booking',
    edit: 'Edit booking',
    empty: 'No bookings yet',
    emptyHint: 'Book a pilgrim onto a package to get started.',
    reference: 'Reference',
    pilgrim: 'Pilgrim',
    package: 'Package',
    bookingDate: 'Booked',
    packagePrice: 'Package price',
    discount: 'Discount',
    total: 'Total',
    paid: 'Paid',
    balance: 'Balance',
    group: 'Group',
    unassigned: 'Unassigned',
    notes: 'Notes',
    confirm: 'Confirm booking',
    cancel: 'Cancel booking',
    cancelConfirm: 'Cancel this booking?',
    cancelWarning: 'The seat is released and any payments stay on record.',
  },

  payments: {
    title: 'Payments',
    subtitle: 'Money in, and what is still owed.',
    record: 'Record payment',
    empty: 'No payments recorded',
    emptyHint: 'Record a payment against an invoice.',
    reference: 'Reference',
    invoice: 'Invoice',
    pilgrim: 'Pilgrim',
    amount: 'Amount',
    paymentDate: 'Date',
    method: 'Method',
    externalReference: 'Transaction reference',
    receipt: 'Receipt',
    recordedBy: 'Recorded by',
    note: 'Note',
    invoices: 'Invoices',
    invoiceNumber: 'Invoice',
    invoiceTotal: 'Total',
    amountPaid: 'Paid',
    balanceDue: 'Balance due',
    dueDate: 'Due',
    totalCollected: 'Total collected',
    totalOutstanding: 'Total outstanding',
    overdueCount: '{count} overdue',
    amountExceedsBalance: 'Amount is more than the outstanding balance.',
  },

  groups: {
    title: 'Groups',
    subtitle: 'Departure cohorts and their readiness.',
    create: 'New group',
    edit: 'Edit group',
    empty: 'No groups yet',
    emptyHint: 'Create a group to organise a departure.',
    name: 'Group name',
    package: 'Package',
    departureDate: 'Departure',
    returnDate: 'Return',
    capacity: 'Capacity',
    guide: 'Guide',
    noGuide: 'No guide assigned',
    members: 'Members',
    membersOf: '{count} of {capacity}',
    seatsRemaining: 'Seats left',
    meetingPoint: 'Meeting point',
    itinerary: 'Itinerary',
    hotelNotes: 'Hotels',
    transportNotes: 'Transport',
    flightNotes: 'Flights',
    notes: 'Notes',
    readiness: 'Departure readiness',
    ready: 'Ready to depart',
    notReady: 'Not ready',
    blockedCount: '{count} pilgrim(s) blocked',
    assignPilgrims: 'Assign pilgrims',
    removeFromGroup: 'Remove from group',
    manifest: 'Manifest',
    tabMembers: 'Members',
    tabLogistics: 'Logistics',
    tabReadiness: 'Readiness',
  },

  documents: {
    title: 'Documents',
    subtitle: 'Paperwork status for every pilgrim.',
    upload: 'Upload document',
    review: 'Review',
    approve: 'Approve',
    reject: 'Reject',
    empty: 'No documents yet',
    emptyHint: 'Upload a pilgrim document to track it here.',
    type: 'Document',
    pilgrim: 'Pilgrim',
    expiryDate: 'Expires',
    uploadedAt: 'Uploaded',
    reviewedBy: 'Reviewed by',
    note: 'Note',
    rejectionReason: 'Reason for rejection',
    checklist: 'Checklist',
    expiringSoon: 'Expires before return',
    pendingReview: 'Pending review',
    viewFile: 'View file',
  },

  settings: {
    title: 'Settings',
    subtitle: 'Your agency details.',
    organizationName: 'Agency name',
    country: 'Country',
    currency: 'Default currency',
    timezone: 'Timezone',
    contactEmail: 'Contact email',
    contactPhone: 'Contact phone',
    saved: 'Changes saved.',
  },

  status: {
    // Package
    DRAFT: 'Draft',
    ACTIVE: 'Active',
    SOLD_OUT: 'Sold out',
    // Booking / pilgrim / group share several of these
    PENDING: 'Pending',
    CONFIRMED: 'Confirmed',
    CANCELLED: 'Cancelled',
    COMPLETED: 'Completed',
    LEAD: 'Lead',
    REGISTERED: 'Registered',
    TRAVELLING: 'Travelling',
    PLANNING: 'Planning',
    OPEN: 'Open',
    READY: 'Ready',
    // Invoice
    UNPAID: 'Unpaid',
    PARTIALLY_PAID: 'Partially paid',
    PAID: 'Paid',
    OVERDUE: 'Overdue',
    // Document
    MISSING: 'Missing',
    UPLOADED: 'Uploaded',
    UNDER_REVIEW: 'Under review',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    EXPIRED: 'Expired',
    // Visa
    NOT_STARTED: 'Not started',
    SUBMITTED: 'Submitted',
  },

  enum: {
    UMRAH: 'Umrah',
    HAJJ: 'Hajj',
    MALE: 'Male',
    FEMALE: 'Female',
    CASH: 'Cash',
    MPESA: 'M-Pesa',
    BANK_TRANSFER: 'Bank transfer',
    CARD: 'Card',
    PASSPORT: 'Passport',
    PASSPORT_PHOTO: 'Passport photo',
    VISA: 'Visa',
    VACCINATION: 'Vaccination certificate',
    INSURANCE: 'Travel insurance',
    CONTRACT: 'Signed contract',
  },
} as const;
